# Generated by Django 4.2.25 on 2025-10-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('experience_years', models.FloatField(blank=True, help_text='Required minimal experience in years', null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=32)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'indexes': [models.Index(fields=['city'], name='jobs_vacanc_city_4f68e8_idx'), models.Index(fields=['employment_type'], name='jobs_vacanc_employm_979a30_idx')],
            },
        ),
    ]
