# Generated by Django 4.2.25 on 2025-10-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='0.0 - 100.0')),
                ('reasons', models.JSONField(blank=True, default=list, help_text='List of reasons or mismatches')),
                ('summary', models.TextField(blank=True, help_text='Short text summary for employer')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relevance', to='candidates.application')),
            ],
            options={
                'verbose_name': 'Результат релевантности',
                'verbose_name_plural': 'Результаты релевантности',
            },
        ),
    ]
