# Generated by Django 4.2.25 on 2025-10-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Доп. данные, например raw form payload')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('resume_text', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('education', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx'), models.Index(fields=['city'], name='candidates__city_c40f02_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('bot', 'bot'), ('candidate', 'candidate')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidates.application')),
            ],
            options={
                'verbose_name': 'Сообщение бота/кандидата',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.vacancy'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['vacancy'], name='candidates__vacancy_f10ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='candidates__candida_911d16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'candidate')},
        ),
    ]
